-- CreateTable
CREATE TABLE "VaultType" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "VaultValues" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "VaultTypeId" INTEGER NOT NULL,
    CONSTRAINT "VaultValues_VaultTypeId_fkey" FOREIGN KEY ("VaultTypeId") REFERENCES "VaultType" ("Id") ON DELETE RESTRICT ON UPDATE CASCADE
);
